---
title: "Missões PrInt UFV"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: 
      version: 4
      bootswatch: united
---


```{r setup, include=FALSE}
library(flexdashboard)
library(gsheet)
library(tidyverse)
library(crosstalk)
library(DT)
library(plotly)
library(RColorBrewer)
library(htmltools)
library(leaflet)

Sys.setlocale("LC_ALL", "pt_BR.UTF-8")

dat1 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1mi4rkT8qr3b-5JlB4ZF9TNE6N3AKWjlLlZ2UqOVYkGw/edit?usp=sharing")


set.seed(1000)
dat1$Latitude <- round(jitter(dat1$Latitude, factor = 1, amount = 0.1), 4)
dat1$Longitude <- round(jitter(dat1$Longitude, factor = 1, amount = 0.1), 4)

sd <- SharedData$new(dat1)
```



Inputs {.sidebar}
-------------------------------------

### Filtros

```{r}

  filter_slider("Ano", "Ano da missão", sd, ~ano, round = TRUE)
  
  filter_select("Tipo de Missão", "Tipo de Missão", sd, ~Tipo, multiple = TRUE)
   filter_select("Nome da missão", "Nome da missão institucional", sd, ~missao_nome, multiple = TRUE)
  filter_select("País", "País", sd, ~País, multiple = TRUE)
   filter_select("Tema", "Tema", sd, ~tema, multiple = TRUE)
   filter_select("Projeto", "Projeto", sd, ~projeto, multiple = TRUE)
```


Row {.tabset .tabset-fade}
-------------------------------------
    
### <i class="fa fa-map" aria-hidden="true"></i> Mapa de missões
    
```{r}

library(RColorBrewer)
library(htmltools)
pal <- colorFactor("Set2", domain = c("Missão institucional", 
                                      "Missão individual",
                                      "Bolsa PDSE",
                                      "Bolsa PVE Júnior",
                                      "Bolsa PVE Sênior"))


leaflet(data = sd, width = "100%") %>%
  setView(-1, -1, zoom = 2) %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles("OpenTopoMap", group = "Terrain") %>%
  addScaleBar("bottomright") %>%
  addProviderTiles(providers$CartoDB.Voyager, group = "Default") %>%
  addLayersControl(
    baseGroups = c("Default", "Aerial", "Terrain"),
    
    options = layersControlOptions(collapsed = T)
  ) %>%
  
  addCircleMarkers(
  
    radius = 6,
    group = "Tipo",
    fillOpacity = 0.9,
    weight = 0.5,
    color = "white",
     fillColor = ~pal(Tipo),
    label = paste(dat1$Nome, "+ informações"),
  
    
    popup = paste(
      "<h3>Sobre a missão</h3>",
      "Tipo:", dat1$"Tipo", "<br>",
      "Tema:", dat1$"tema", "<br>",
       "Local:", dat1$"Local", "<br>",
       "País:", dat1$"País", "<br>",
       "Data:", dat1$"data_ida", "<br>",
       "Instituição:", dat1$"instituição", "<br>",
       "Participantes:", dat1$"participantes", "<br>"
      )

  ) %>%

  addLegend("bottomleft",
    pal = pal,
    values = ~Tipo,
    title = "Tipo de missão",
    opacity = 1)%>%
    
 

  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 2",
    onClick=JS("function(btn, map){ map.setZoom(2); }"))) 



```
   

### <i class="fa fa-table" aria-hidden="true"></i> Dados sobre as missões

```{r}
dat2 <- dat1 |> 
  select(Tipo, tema, instituição, Local, País, ano, data_ida, participantes)
sd2 <- SharedData$new(dat2)


 datatable(sd, 
           escape = FALSE,
           rownames = FALSE,
           extensions = c("Buttons"),
             class = 'table-bordered table-condensed',
           options = list(
              pageLength = 20,
    dom = "Bfrtip", buttons = c("excel")))


```   
 


### <i class="fa fa-bar-chart" aria-hidden="true"></i> Visitas por país

```{r}
p2 <- dat1 |> 
  count(Tipo, País) |> 
  ggplot(aes(País, n, fill = Tipo))+
  geom_col()+
  coord_flip()+
  labs(y = "Número de locais visitados", x = "")+
  theme_light()+
  scale_fill_brewer(palette = "Set2")
ggplotly(p2)
```



### <i class="fa fa-bar-chart" aria-hidden="true"></i> Visitas por Temas


```{r}
p2 <- dat1 |> 
  count(Tipo, tema) |> 
  filter(tema != "Todos os temas") |> 
  ggplot(aes(tema, n, fill = Tipo))+
  geom_col()+
  labs(y = "Número de locais visitados", x = "")+
  theme_light()+
  coord_flip()+
  scale_fill_brewer(palette = "Set2")
ggplotly(p2)
```




